const express = require('express');
const router = express.Router();
const sql = require('mssql');

module.exports = (pool) => {       

    router.post('/', async (req, res) => {
        const transaction = new sql.Transaction(pool);
        
        try {
            const { 
                CompanyName, 
                CompanyAddress, 
                CompanyContact,
                FirstName,
                LastName,
                email,
                phoneNumber,
                password,
                hiredDate = new Date().toISOString().split('T')[0],
                address,
                notes = null,
                role = 'Founder', 
                status = 'Active'
            } = req.body;
    
            // Basic validation
            if (!CompanyName || !CompanyAddress || !CompanyContact) {
                return res.status(400).json({ 
                    success: false, 
                    error: 'All organization fields are required' 
                });
            }
    
            if (!FirstName || !LastName || !email || !password) {
                return res.status(400).json({ 
                    success: false, 
                    error: 'All user fields are required' 
                });
            }
    
            // Email validation
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(email)) {
                return res.status(400).json({ 
                    success: false, 
                    error: 'Invalid email format' 
                });
            }
    
            // Start transaction
            await transaction.begin();
    
            // 1️⃣ Check if email already exists
            const checkEmail = await new sql.Request(transaction)
                .input('email', sql.NVarChar, email)
                .query(`SELECT email FROM Users WHERE email = @email`);
    
            if (checkEmail.recordset.length > 0) {
                await transaction.rollback();
                return res.status(400).json({ 
                    success: false, 
                    error: 'Email already registered' 
                });
            }

            const checkCompanyName = await new sql.Request(transaction)
                .input('name',sql.NVarChar,CompanyName)
                .query('select name from Organization where name = @name');

            if(checkCompanyName.recordset.length > 0){
                await transaction.rollback();
                return res.status(400).json({
                    success: false,
                    error:'Company Name is already in use. Find something original'
                })
            }
    
            // 2️⃣ Insert organization (trigger handles CompanyCode)
            const insertOrg = await new sql.Request(transaction)
                .input('CompanyName', sql.NVarChar, CompanyName)
                .input('CompanyAddress', sql.NVarChar, CompanyAddress)
                .input('CompanyContact', sql.NVarChar, CompanyContact)
                .query(`
                    INSERT INTO Organization (name, address, phone)
                    VALUES (@CompanyName, @CompanyAddress, @CompanyContact);
    
                    SELECT SCOPE_IDENTITY() AS ID;
                `);
    
            const orgID = insertOrg.recordset[0].ID;
    
            // 3️⃣ Get CompanyCode generated by trigger
            const getCode = await new sql.Request(transaction)
                .input('ID', sql.Int, orgID)
                .query(`SELECT CompanyCode FROM Organization WHERE id = @ID`);
    
            const CompanyCode = getCode.recordset[0].CompanyCode;
    
            // 4️⃣ Hash password (recommended - install bcrypt: npm install bcrypt)
            // const bcrypt = require('bcrypt');
            // const hashedPassword = await bcrypt.hash(password, 10);
    
            // 5️⃣ Insert founder user
            const insertFounder = await new sql.Request(transaction)
                .input('FirstName', sql.NVarChar, FirstName)
                .input('LastName', sql.NVarChar, LastName)
                .input('email', sql.NVarChar, email)
                .input('phoneNumber', sql.NVarChar, phoneNumber)
                .input('password', sql.NVarChar, password) // Use hashedPassword here
                .input('CompanyCode', sql.NVarChar, CompanyCode)
                .input('role', sql.NVarChar, role)
                .input('status', sql.NVarChar, status)
                .input('hiredDate', sql.Date, hiredDate)
                .input('address', sql.NVarChar, address)
                .input('notes', sql.NVarChar, notes)
                .query(`
                    INSERT INTO Users (FirstName, LastName, email, phoneNumber, password, CompanyCode, role, status, hiredDate, address, notes)
                    VALUES (@FirstName, @LastName, @email, @phoneNumber, @password, @CompanyCode, @role, @status, @hiredDate, @address, @notes);
    
                    SELECT SCOPE_IDENTITY() AS FounderID;
                `);
    
            const FounderID = insertFounder.recordset[0].FounderID;
    
            // 6️⃣ Update Organization.CreatedBy with the new founder
            await new sql.Request(transaction)
                .input('ID', sql.Int, orgID)
                .input('CreatedBy', sql.Int, FounderID)
                .query(`UPDATE Organization SET CreatedBy = @CreatedBy WHERE id = @ID`);
    
            // Commit transaction - all operations succeeded
            await transaction.commit();
    
            res.status(201).json({
                success: true,
                message: 'Organization and Founder created successfully',
                data: {
                    CompanyCode,
                    orgID,
                    FounderID
                }
            });
    
        } catch (error) {
            // Rollback transaction on any error
            try {
                if (transaction._aborted === false) {
                    await transaction.rollback();
                }
            } catch (rollbackError) {
                console.error('Rollback error:', rollbackError);
            }
            
            console.error('=== DETAILED ERROR ===');
            console.error('Error message:', error.message);
            console.error('Error code:', error.code);
            console.error('Error number:', error.number);
            console.error('Error state:', error.state);
            console.error('Error stack:', error.stack);
            console.error('======================');
            
            res.status(500).json({ 
                success: false, 
                error: 'Failed to create organization and founder',
                details: error.message,
                code: error.code,
                number: error.number
            });
        }
    });

    
    // PUT profile update
    router.put('/profile', async (req, res) => {
        try {
    
            const { company } = req.body;
    
            await pool.request()
                .input('name', sql.NVarChar, company.name)
                .input('address', sql.NVarChar, company.address)
                .input('phone', sql.NVarChar, company.phone)
                .input('CompanyCode', sql.NVarChar, company.companyCode)
                .query(`
                   
                    UPDATE Organization
                    SET name=@name, address=@address, phone=@phone
                    WHERE CompanyCode=@CompanyCode;
                `);
    
            res.json({ success: true });
    
        } catch (err) {
            console.error(err);
            res.status(500).json({ success: false, error: "Server error" });
        }
    });

    router.get('/:CompanyCode', async (req, res) => {

        const{CompanyCode} = req.params;

        try {
            const result = await pool.request()
                .input('CompanyCode', sql.NVarChar, CompanyCode)
                .query(`
                    SELECT o.id, o.name, o.address, o.phone, u.FirstName + ' ' + u.LastName as CreatedBy, o.CompanyCode
                    FROM Organization o join Users u on o.CreatedBy = u.id
                    WHERE o.CompanyCode = @CompanyCode
                `);

            const getCode = await pool.request()
                    .input('CompanyCode',sql.NVarChar, CompanyCode)
                    .query(`Select * from Organization where CompanyCode = @CompanyCode`);


            res.json({ success: true, data: result.recordset[0], exists: !!getCode.recordset[0] });
        } catch (err) {
            console.error("Get organization error:", err);
            res.status(500).json({ success: false, error: "Server Error" });
        }
    });

    
    
    
    
    return router;
};
